In [1]:
import torch
import torch.nn.functional as F

In [8]:
torch.set_printoptions(sci_mode=False)

In [2]:
example = torch.tensor([-5., -1, 0, 1, 5])

In [3]:
F.relu(example)

tensor([0., 0., 0., 1., 5.])

In [4]:
torch.sigmoid(example)

tensor([0.0067, 0.2689, 0.5000, 0.7311, 0.9933])

In [5]:
torch.tanh(example)

tensor([-0.9999, -0.7616,  0.0000,  0.7616,  0.9999])

In [9]:
torch.softmax(example, 0)

tensor([    0.0000,     0.0024,     0.0066,     0.0178,     0.9732])

In [12]:
twod = torch.tensor([ 
    [1., 10, 2], 
    [20, 1, 1] 
])

In [13]:
torch.softmax(twod, 1)

tensor([[    0.0001,     0.9995,     0.0003],
        [    1.0000,     0.0000,     0.0000]])