In [1]:
import torch

In [2]:
torch.rand(10)

tensor([0.4979, 0.6207, 0.9038, 0.2059, 0.2843, 0.3506, 0.5463, 0.5876, 0.2186,
        0.3910])

In [3]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

In [4]:
print(a)
b

tensor([[0.1326, 0.6091],
        [0.4390, 0.9723]])


tensor([[0.0786, 0.9051],
        [0.9926, 0.4576]])

In [5]:
a + b

tensor([[0.2112, 1.5141],
        [1.4316, 1.4300]])

In [6]:
a * b

tensor([[0.0104, 0.5513],
        [0.4357, 0.4450]])

In [7]:
a @ b

tensor([[0.6150, 0.3987],
        [0.9997, 0.8423]])

In [8]:
torch.mm(a, b)

tensor([[0.6150, 0.3987],
        [0.9997, 0.8423]])

In [9]:
torch.cat((a, b))

tensor([[0.1326, 0.6091],
        [0.4390, 0.9723],
        [0.0786, 0.9051],
        [0.9926, 0.4576]])

In [10]:
a.shape

torch.Size([2, 2])

In [11]:
c = torch.tensor([1.5, 0, -2, 2.2])
c.shape

torch.Size([4])